version: 3

tasks:
  setup-shuttle:
    desc: setup project
    cmd: cp .env_example Secrets.toml

  run:
    desc: run application
    cmd: cargo shuttle run

  build:
    desc: build application
    cmd: cargo build

  deploy-shuttle:
    desc: deploy application
    cmd: cargo shuttle deploy

  check:
    desc: check rust code
    cmds:
      - cargo clippy
      - cargo check

  fmt:
    desc: format code
    cmds:
      - cargo fmt
      - cargo clippy --fix --allow-dirty --allow-staged
